// <auto-generated />
using System;
using Inno.RngDNDTool.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inno.RngDNDTool.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220807141208_UpdateCharacterProperties")]
    partial class UpdateCharacterProperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Acrobatics")
                        .HasColumnType("int");

                    b.Property<string>("Allignment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnimalHandling")
                        .HasColumnType("int");

                    b.Property<int>("Arcana")
                        .HasColumnType("int");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("Athletics")
                        .HasColumnType("int");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bonds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("CurrentWeightCarried")
                        .HasColumnType("int");

                    b.Property<int>("Deception")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Flaws")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("History")
                        .HasColumnType("int");

                    b.Property<string>("Ideals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Initiative")
                        .HasColumnType("int");

                    b.Property<int>("InitiativeBonus")
                        .HasColumnType("int");

                    b.Property<int>("Insight")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Intimidation")
                        .HasColumnType("int");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Investigation")
                        .HasColumnType("int");

                    b.Property<bool>("IsEncumbered")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxCarryWeight")
                        .HasColumnType("int");

                    b.Property<int>("Medicine")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nature")
                        .HasColumnType("int");

                    b.Property<int>("PassiveWisdom")
                        .HasColumnType("int");

                    b.Property<int>("Perception")
                        .HasColumnType("int");

                    b.Property<int>("Performance")
                        .HasColumnType("int");

                    b.Property<string>("PersonalTraits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Persuasion")
                        .HasColumnType("int");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.Property<int>("RequiredMultiClassLevel")
                        .HasColumnType("int");

                    b.Property<int>("SleightOfHand")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Stealth")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Survival")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29bcd574-1436-4a71-a750-4484d10cb105"),
                            Acrobatics = 5,
                            Allignment = "Lawfull Evil",
                            AnimalHandling = 2,
                            Arcana = 1,
                            ArmorClass = 15,
                            Athletics = 0,
                            Background = "Acolyte",
                            Bonds = "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.",
                            Charisma = 8,
                            Constitution = 14,
                            CurrentWeightCarried = 0,
                            Deception = -1,
                            Dexterity = 17,
                            Experience = 0,
                            Flaws = "I am suspicious of strangers and expect the worst in them.",
                            History = 1,
                            Ideals = "Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld.(Lawfull)",
                            Initiative = 0,
                            InitiativeBonus = 0,
                            Insight = 4,
                            Intelligence = 12,
                            Intimidation = -1,
                            InventoryId = new Guid("82b556d3-ecef-40d6-aaae-12bcf93592d2"),
                            Investigation = 1,
                            IsEncumbered = false,
                            Level = 1,
                            MaxCarryWeight = 100,
                            Medicine = 2,
                            Name = "Copuul",
                            Nature = 1,
                            PassiveWisdom = 14,
                            Perception = 4,
                            Performance = -1,
                            PersonalTraits = "I see omens in every event and action. The gods try to speak to us, we just need to listen.",
                            Persuasion = -1,
                            ProficiencyBonus = 2,
                            Race = "Grung",
                            Religion = 3,
                            RequiredMultiClassLevel = 5,
                            SleightOfHand = 3,
                            Speed = 25,
                            Stealth = 5,
                            Strength = 10,
                            Survival = 2,
                            Wisdom = 14
                        });
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Classes.Abilities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CharacterClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Classes.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CharacterClasses");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CharacterClass");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Inventories.Base.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxCoinStack")
                        .HasColumnType("int");

                    b.Property<Guid?>("NpcId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasFilter("[CharacterId] IS NOT NULL");

                    b.HasIndex("NpcId")
                        .IsUnique()
                        .HasFilter("[NpcId] IS NOT NULL");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82b556d3-ecef-40d6-aaae-12bcf93592d2"),
                            CharacterId = new Guid("29bcd574-1436-4a71-a750-4484d10cb105"),
                            MaxCoinStack = 100
                        });
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Armor.Armor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("BodyPlacement")
                        .HasColumnType("int");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Consumables.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodTypes")
                        .HasColumnType("int");

                    b.Property<string>("ItemImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<int>("StatusEffectDurationInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("StatusEffectType")
                        .HasColumnType("int");

                    b.Property<int>("StatusEffectValue")
                        .HasColumnType("int");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Consumables.Potion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PotionType")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<int>("StatusEffectDurationInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("StatusEffectValue")
                        .HasColumnType("int");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Potions");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Consumables.Scroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("RequiredDifficultyClass")
                        .HasColumnType("int");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<Guid?>("SpellId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.ToTable("Scrolls");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Weapons.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<int>("DamageDice")
                        .HasColumnType("int");

                    b.Property<int>("DamageType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<int>("WeaponType")
                        .HasColumnType("int");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Npcs.Base.Npc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Acrobatics")
                        .HasColumnType("int");

                    b.Property<int>("AnimalHandling")
                        .HasColumnType("int");

                    b.Property<int>("Arcana")
                        .HasColumnType("int");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("Athletics")
                        .HasColumnType("int");

                    b.Property<int>("BehaviorType")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Deception")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("History")
                        .HasColumnType("int");

                    b.Property<int>("Initiative")
                        .HasColumnType("int");

                    b.Property<int>("Insight")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Intimidation")
                        .HasColumnType("int");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Investigation")
                        .HasColumnType("int");

                    b.Property<int>("Medicine")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nature")
                        .HasColumnType("int");

                    b.Property<int>("PassiveWisdom")
                        .HasColumnType("int");

                    b.Property<int>("Perception")
                        .HasColumnType("int");

                    b.Property<int>("Performance")
                        .HasColumnType("int");

                    b.Property<int>("Persuasion")
                        .HasColumnType("int");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("int");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.Property<int>("SleightOfHand")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Stealth")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Survival")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Spells.Base.BaseSpell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttackRadiusInMeters")
                        .HasColumnType("int");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Concentration")
                        .HasColumnType("bit");

                    b.Property<int>("DamageRoll")
                        .HasColumnType("int");

                    b.Property<int>("DamageType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredSavingThrowType")
                        .HasColumnType("int");

                    b.Property<bool>("Ritual")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndMaps.BaseMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaseMap");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "faa97b2c-8771-4aea-b899-e560fd892455",
                            AccessFailedCount = 0,
                            Adress = "Default",
                            ConcurrencyStamp = "36712751-8e38-4f4a-a40f-3564c2193800",
                            Email = "Rng@Admin.rng",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Super",
                            LockoutEnabled = false,
                            NormalizedEmail = "RNG@ADMIN.RNG",
                            NormalizedUserName = "RNGADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEIgc3P+4imE+3Uh6X+uWrZ5KAeSne7NXXwHxHJyvcoArn+YOIu4igLd1l4vEFUMbYg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c9c33eb3-d2a6-41eb-b251-0d810ecf3a53",
                            TwoFactorEnabled = false,
                            UserName = "RngAdmin"
                        });
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.ApplicationUserCharacters", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("ApplicationUserCharacters");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.ApplicationUserMaps", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId", "MapId");

                    b.HasIndex("MapId");

                    b.ToTable("ApplicationUserMaps");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.CharactersClasses", b =>
                {
                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CharacterClassId", "CharacterId");

                    b.ToTable("CharactersClasses");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.CharacterSpells", b =>
                {
                    b.Property<Guid>("SpellId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SpellId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSpells");

                    b.HasData(
                        new
                        {
                            SpellId = new Guid("c16a9a18-a96d-47fe-a49e-0ee0088e7e2d"),
                            CharacterId = new Guid("29bcd574-1436-4a71-a750-4484d10cb105")
                        },
                        new
                        {
                            SpellId = new Guid("9fcd8482-df14-4e47-8433-ffae30e74735"),
                            CharacterId = new Guid("29bcd574-1436-4a71-a750-4484d10cb105")
                        },
                        new
                        {
                            SpellId = new Guid("6e42ce23-9081-4b91-b38d-a77f1436baff"),
                            CharacterId = new Guid("29bcd574-1436-4a71-a750-4484d10cb105")
                        },
                        new
                        {
                            SpellId = new Guid("d12be89a-e0df-441f-b1c2-4f91557b4d1c"),
                            CharacterId = new Guid("29bcd574-1436-4a71-a750-4484d10cb105")
                        });
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.InventoryArmors", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArmorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InventoryId", "ArmorId");

                    b.HasIndex("ArmorId");

                    b.ToTable("InventoryArmors");

                    b.HasData(
                        new
                        {
                            InventoryId = new Guid("82b556d3-ecef-40d6-aaae-12bcf93592d2"),
                            ArmorId = new Guid("a66f53e9-605d-4ede-af78-f6cc985203ef")
                        });
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.InventoryFoods", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InventoryId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("InventoryFoods");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.InventoryPotions", b =>
                {
                    b.Property<Guid>("PotionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PotionId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryPotions");

                    b.HasData(
                        new
                        {
                            PotionId = new Guid("b9f5c577-d2f8-4c39-ade1-ba5f33684dca"),
                            InventoryId = new Guid("82b556d3-ecef-40d6-aaae-12bcf93592d2")
                        });
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.InventoryScrolls", b =>
                {
                    b.Property<Guid>("ScrollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScrollId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryScrolls");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.InventoryWeapons", b =>
                {
                    b.Property<Guid>("WeaponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WeaponId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryWeapons");

                    b.HasData(
                        new
                        {
                            WeaponId = new Guid("8ecd50d4-9079-4428-9ec5-f45b5abce6c7"),
                            InventoryId = new Guid("82b556d3-ecef-40d6-aaae-12bcf93592d2")
                        });
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.NpcClasses", b =>
                {
                    b.Property<Guid>("NpcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NpcId", "CharacterClassId");

                    b.HasIndex("CharacterClassId");

                    b.ToTable("NpcClasses");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.NpcSpells", b =>
                {
                    b.Property<Guid>("SpellId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SpellId", "NpcId");

                    b.HasIndex("NpcId");

                    b.ToTable("NpcSpells");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Classes.CoreClass", b =>
                {
                    b.HasBaseType("Inno.RngDNDTool.Core.Entities.DndEntities.Classes.CharacterClass");

                    b.Property<int>("HitDice")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("CoreClass");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Classes.Proficiencies", b =>
                {
                    b.HasBaseType("Inno.RngDNDTool.Core.Entities.DndEntities.Classes.CharacterClass");

                    b.Property<int>("ArmorProficiencies")
                        .HasColumnType("int");

                    b.Property<int>("WeaponProficiencies")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Proficiencies");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Classes.Abilities", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Classes.CharacterClass", null)
                        .WithMany("Abilities")
                        .HasForeignKey("CharacterClassId");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Inventories.Base.Inventory", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Characters.Character", "Character")
                        .WithOne("Inventory")
                        .HasForeignKey("Inno.RngDNDTool.Core.Entities.DndEntities.Inventories.Base.Inventory", "CharacterId");

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Npcs.Base.Npc", "Npc")
                        .WithOne("Inventory")
                        .HasForeignKey("Inno.RngDNDTool.Core.Entities.DndEntities.Inventories.Base.Inventory", "NpcId");

                    b.Navigation("Character");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Armor.Armor", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Characters.Character", null)
                        .WithMany("Armor")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Consumables.Scroll", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Spells.Base.BaseSpell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellId");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.ApplicationUserCharacters", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserCharacters")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Characters.Character", "Character")
                        .WithMany("ApplicationUserCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.ApplicationUserMaps", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserMaps")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndMaps.BaseMap", "Map")
                        .WithMany("ApplicationUserMaps")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.CharactersClasses", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Characters.Character", "Character")
                        .WithMany("CharactersClasses")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Classes.CharacterClass", "CharacterClass")
                        .WithMany("CharactersClasses")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.CharacterSpells", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Characters.Character", "Character")
                        .WithMany("CharacterSpells")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Spells.Base.BaseSpell", "Spell")
                        .WithMany("CharacterSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.InventoryArmors", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Armor.Armor", "Armor")
                        .WithMany("InventoryArmors")
                        .HasForeignKey("ArmorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Inventories.Base.Inventory", "Inventory")
                        .WithMany("InventoryArmors")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armor");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.InventoryFoods", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Consumables.Food", "Food")
                        .WithMany("InventoryFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Inventories.Base.Inventory", "Inventory")
                        .WithMany("InventoryFoods")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.InventoryPotions", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Inventories.Base.Inventory", "Inventory")
                        .WithMany("InventoryPotions")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Consumables.Potion", "Potion")
                        .WithMany("InventoryPotions")
                        .HasForeignKey("PotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Potion");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.InventoryScrolls", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Inventories.Base.Inventory", "Inventory")
                        .WithMany("InventoryScrolls")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Consumables.Scroll", "Scroll")
                        .WithMany("InventoryScrolls")
                        .HasForeignKey("ScrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Scroll");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.InventoryWeapons", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Inventories.Base.Inventory", "Inventory")
                        .WithMany("InventoryWeapons")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Weapons.Weapon", "Weapon")
                        .WithMany("InventoryWeapons")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.NpcClasses", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Classes.CharacterClass", "CharacterClass")
                        .WithMany("NpcClasses")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Npcs.Base.Npc", "Npc")
                        .WithMany("NpcClasses")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Joins.NpcSpells", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Npcs.Base.Npc", "Npc")
                        .WithMany("NpcSpells")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.DndEntities.Spells.Base.BaseSpell", "Spell")
                        .WithMany("NpcSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Npc");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inno.RngDNDTool.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Inno.RngDNDTool.Core.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Characters.Character", b =>
                {
                    b.Navigation("ApplicationUserCharacters");

                    b.Navigation("Armor");

                    b.Navigation("CharacterSpells");

                    b.Navigation("CharactersClasses");

                    b.Navigation("Inventory")
                        .IsRequired();
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Classes.CharacterClass", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("CharactersClasses");

                    b.Navigation("NpcClasses");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Inventories.Base.Inventory", b =>
                {
                    b.Navigation("InventoryArmors");

                    b.Navigation("InventoryFoods");

                    b.Navigation("InventoryPotions");

                    b.Navigation("InventoryScrolls");

                    b.Navigation("InventoryWeapons");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Armor.Armor", b =>
                {
                    b.Navigation("InventoryArmors");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Consumables.Food", b =>
                {
                    b.Navigation("InventoryFoods");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Consumables.Potion", b =>
                {
                    b.Navigation("InventoryPotions");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Consumables.Scroll", b =>
                {
                    b.Navigation("InventoryScrolls");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Items.Weapons.Weapon", b =>
                {
                    b.Navigation("InventoryWeapons");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Npcs.Base.Npc", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("NpcClasses");

                    b.Navigation("NpcSpells");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndEntities.Spells.Base.BaseSpell", b =>
                {
                    b.Navigation("CharacterSpells");

                    b.Navigation("NpcSpells");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.DndMaps.BaseMap", b =>
                {
                    b.Navigation("ApplicationUserMaps");
                });

            modelBuilder.Entity("Inno.RngDNDTool.Core.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUserCharacters");

                    b.Navigation("ApplicationUserMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
